name: Fodder Pro
favicon: null
layout_spectrum: 0.38465760461986065
typography_spectrum: 0.12494686292484403
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7553709917701781
  lightness: 0.10007042274810374
  saturation: 0.41832308168523014
  rhythmicContrast: 0.3317575752735138
purpose: []
